name: build library 🏗️
on:
  push:
  workflow_call:
    node_version:
      description: "Node Version to use for building the library"
      default: "18"
      type: string
    artifact_path:
      description: "Artifact path to persist the build"
      default: "prompt-manners-0.0.0.tgz"
      type: string
env:
  NODE_VERSION: 18
  ARTIFACT_PATH: "prompt-manners-*.tgz"

jobs:
  build_library:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/node-setup
        with:
          node-version: ${{ inputs.node_version || env.NODE_VERSION }}

      - run: npm run build

      - run: npm pack

      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: library-build-dist
          path: ${{ inputs.artifact_path || env.ARTIFACT_PATH }}
