name: version bump ➕

on:
  workflow_dispatch:
    inputs:
      next_version:
        description: "Version to bump the package to"
        required: true

env:
  NODE_VERSION: 18

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Bump version
        shell: bash
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ inputs.next_version }} -m "build(version): Bump version to %s"
          git push --follow-tags
